### ISSUE TITLE
Get devtools::install_github() to work

### ISSUE THREAD

**Issue by mloop** [mloop/lodr#12]

**Comment by kmdono02** [comment]
Works on my local machine (Windows 10 OS)

**Comment by mloop** [comment]
@kmdono02 I was able to fix my compiler and get openMP support. However, when I got to install it now, it seems like I'm getting c++ style errors. Here is a screen shot. Can you make any sense of this?

<img width="1724" alt="Screen Shot 2019-10-02 at 12 08 21 PM" src="https://user-images.githubusercontent.com/6737937/66061432-7a421f00-e50d-11e9-86fc-791a2800c27e.png">

**Comment by kmdono02** [comment]
I remember seeing those issues on your computer before when using sourceCpp() instead of installing the package itself.  This is strange as I don't see these with my Windows 10 machine.  Do you see the same errors when you try to install the package on the Views VM?
