### ISSUE TITLE
Write at least one unit test for lm_lod

### ISSUE THREAD

**Issue by mloop** [mloop/lodr#6]

**Comment by kmdono02** [comment]
This has been done.  See updated repo, specifically Data subfolder.  I have successfully tested this example as well.

**Comment by kmdono02** [comment]
I'm not sure if this is the same as "test on simmed dataset" so I reopened it.

**Comment by mloop** [comment]
I think the checks that you wrote inside the function for whether the arguments are placed correctly is good enough for this! 👍
