### ISSUE TITLE
Package passes CRAN tests

### ISSUE THREAD

**Issue by mloop** [mloop/lodr#7]

**Comment by mloop** [comment]
Should also provide no warnings. These warnings seem to be important when you create new classes.

**Comment by kmdono02** [comment]
After running check() for CRAN test, result is 0 errors, 0 warnings, and 1 note.  The note is simply that the number of arguments for the 2 Rcpp functions (LOD_fit, LOD_bootstrap_fit) is large so the documentation in the PDF reference manual on CRAN will truncate the argument lists for these functions.  Thus, I feel the package passes.
